# Generated by Django 3.0.5 on 2020-04-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_author_moments_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='icon_id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
    ]
