# Generated by Django 3.0.5 on 2020-04-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200411_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='recommend',
            name='author_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
