# Generated by Django 3.0.5 on 2020-04-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200411_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moments',
        ),
    ]
