# Generated by Django 3.0.5 on 2020-04-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_delete_moments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='author',
        ),
    ]
