# Generated by Django 3.0.5 on 2020-04-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='identifier',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
