# Generated by Django 3.0.5 on 2020-04-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
